### PR TITLE
Issue #321: Replace built-in PHP server usage with WSL.

### PR DESCRIPTION
**Pull request by alexmerlin**

### CODE REVIEW

**Review by arhimede — COMMENTED** [review]
It was tested from a fresh wsl container to a functional frontend ?

**Comment by alexmerlin** [comment]
> It was tested from a fresh wsl container to a functional frontend ?

Yes, I just tested, but...

**Note**:
With the changes from this PR the developer would have to set manually the correct URL stored in the `$baseUrl` variable.
We could avoid this step if we use the HTT_HOST and generate the URL automatically by setting:
```
$baseUrl = 'http://' . $_SERVER['HTTP_HOST'];
```
in the **local.php** file.

**Review by arhimede — CHANGES_REQUESTED** [review]
in local.php.dist 
cocatenate $_SERVER['REQUEST_SCHEME'] with HTTP_HOST

**Review by arhimede — CHANGES_REQUESTED** [review]
$baseUrl = 'http://localhost:8080'; 
$baseUrl = 'http://frontend.dev';

**Pull request merged**
