### PR TITLE
removed translation feature

### LINKED ISSUE #445: remove Translation feature
but let's prepare it as a separate package

### PR DESCRIPTION
**Pull request by bidi47**

### CODE REVIEW

**Review by alexmerlin — CHANGES_REQUESTED** [review]
There are some language/translation related relics left that need to be removed:
- https://github.com/dotkernel/frontend/blob/issue-445/src/App/templates/layout/default.html.twig#L2: replace variable `{{ language_key }}` with string `en`
- https://github.com/dotkernel/frontend/blob/issue-445/src/App/templates/layout/default.html.twig#L8: replace `V3` with `V5` (not related to this, but should be fixed)
- Delete file https://github.com/dotkernel/frontend/blob/issue-445/src/App/assets/scss/components/_language.scss
- Delete line https://github.com/dotkernel/frontend/blob/issue-445/src/App/assets/scss/index.scss#L13
- Delete line https://github.com/dotkernel/frontend/blob/issue-445/src/App/src/ConfigProvider.php#L74 then adjust the number of spaces before the arrows
- Delete line https://github.com/dotkernel/frontend/blob/issue-445/test/Unit/App/ConfigProviderTest.php#L77

Finally, rebuild `app.js` and `app.css`.

**Comment by bidi47** [comment]
the changes are done - i asked for another review

i must have made the js updates right as you were reviewing because they were already done
there were no other edits to app.js and app.css after i implemented your changes

**Review by alexmerlin — CHANGES_REQUESTED** [review]
Let's try again:

- Delete file https://github.com/dotkernel/frontend/blob/issue-445/src/App/assets/scss/components/_language.scss
- Delete line https://github.com/dotkernel/frontend/blob/issue-445/src/App/assets/scss/index.scss#L13

Finally, rebuild `app.js` and `app.css`.

**Comment by bidi47** [comment]
> Let's try again:
> 
>     * Delete file https://github.com/dotkernel/frontend/blob/issue-445/src/App/assets/scss/components/_language.scss
> 
>     * Delete line https://github.com/dotkernel/frontend/blob/issue-445/src/App/assets/scss/index.scss#L13
> 
> 
> Finally, rebuild `app.js` and `app.css`.

oops, my bad
i read those assets as 'js' instead of 'scss' because they're so similar :)

**Review by alexmerlin — APPROVED** [review]

**Pull request merged**
